version: "2"
services:
    csvserver:
      image: infracloudio/csvserver:latest
      volumes:
      - /csvserver/inputdata:/csvserver/inputdata
      ports:
      - "9393:9300"
      env_file:
      - ./csvserver.env
        
        
